### ISSUE TITLE
Launch "localhost" when images start

### ISSUE THREAD

**Issue by bbollen23** [visdesignlab/loonar#95]
When the client has finished starting, see if we can auto launch client.

**Comment by bbollen23** [comment]
This may not be feasible:
https://stackoverflow.com/questions/54437534/docker-open-a-url-in-the-host-browser

In general, Docker does not have access to the host's GUI so trying to call commands like "xdg-open" dont' work. The solutions that people have came up with all involve additional steps outside the image.

**Comment by Dev-Lan** [comment]
I think I misremembered this. When I tried again it didn't open automatically. It did have this link here in the docker desktop application, from this repo (https://github.com/docker/welcome-to-docker).

It would be nice if we had a link like this, but not required.

![image](https://github.com/user-attachments/assets/e75e094f-da2b-4644-ac32-ed08f814fb58)

We can ignore the launch localhost request as Devin being wrong :)

**Comment by bbollen23** [comment]
@Dev-Lan unfortunately, that link only shows up when you map ports (which is done at the running stage), which would mean that you’d have to input more crap. But, if you expand the build files set of containers, you’ll see it has the link for the client by default.

I’ve also added and output in the build script so that when it’s done starting the containers, it prints “Visit {this url} to use the application”. And this will be outputted in the logs of the docker container that comes from the image we distribute in docker hub.
